### ISSUE TITLE
Second parameter to mul, div, percent should not be an amount

### ISSUE THREAD

**Issue by mjtodd** [ikr/money-math#8]
Hi, I've been looking into using this module, and firstly completely understand the need to pass amounts in a fixed format, converting using floatToAmount as needed.

I don't understand though why the second parameter of functions like mul, div, percent should be an amount. Shouldn't this be a regular number? I can't multiply 2 amounts of money together, but I can multiply an amount of money by a quantity to get a total amount of money, so amount * number = amount

Does this make sense? Even if the second parameter still has to be a string to guarantee precision, I don't it should adhere to the same regex i.e. I want to be about to multiply an amount by '1.2' and get the expected result without first having to convert that to '1.20', which I think is counter intuitive

**Comment by ikr** [comment]
Hi @mjtodd 

The library implements an [Algebraic system](https://en.wikipedia.org/wiki/Algebraic_structure) for amounts as the carrier set. That's why all the operations expect amounts, and return amounts. That by itself has nothing to do with the unit of measurement – the money. Think of it as multiplying just the two members of the carrier set looking like `XXX.XX`. When calculations take place, the units of measurement (sort-of the physical meaning of values) may change along the way, just like when you evaluate a physical formula with numeric values of the variables. Thus, money-math is just the algebra; it doesn't track any units.

Does that help?

**Comment by mjtodd** [comment]
Yes, makes perfect sense - thanks!
